name: Build Android APK

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Скачивание кода
      uses: actions/checkout@v4

    - name: ⚙️ Настройка Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: 🎨 Сборка стилей Tailwind CSS v4
      run: |
        npm install @tailwindcss/cli
        npx @tailwindcss/cli -i ./input.css -o ./www/styles.css --minify

    - name: 📱 Синхронизация Capacitor (Web -> Android)
      run: |
        npm install @capacitor/core @capacitor/cli @capacitor/android
        npx cap sync android

    - name: ☕ Настройка Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: 🔨 Сборка APK
      working-directory: ./android
      run: |
        # Даем права на запуск сборщика
        chmod +x ./gradlew
        # Собираем отладочный APK
        ./gradlew assembleDebug

    - name: 📦 Сохранение готового APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
